### ISSUE TITLE
Neptune E-Coder

### ISSUE THREAD

**Issue by kissste** [BobPrust/Water-Meter-Neptune-E-Coder#1]
Hi Bob, 

Could you please upload the code as a text file? 

These PDFs are handy, but the code needs to be retyped.

Thank you,

**Comment by TheCre8r** [comment]
+1

**Comment by kissste** [comment]
I have posted it here:

https://github.com/kissste/Water-Meter-Neptune-E-Coder/blob/master/water-meter-neptune-e-coder.ino
